---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - passwd

- name: 'file ensure passwd'
  file:
    state: 'file'
    dest: "{{file_dst_passwd}}"
    mode: "{{file_mode_passwd}}"
    owner: "{{file_owner_passwd}}"
    group: "{{file_group_passwd}}"
  tags:
    - passwd
