---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - hostname

- name: 'package install hostname'
  package:
    state: 'present'
    name: "{{package_name_hostname}}"
    install_recommends: 'no'
  tags:
    - hostname

- name: 'command get chassis'
  shell: "{{command_cmd_get_chassis}}"
  register: register_chassis
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set chassis'
  command: "{{command_cmd_set_chassis}}"
  when: not (hostname_chassis == '') and not (register_chassis.stdout == hostname_chassis)
  tags:
    - hostname

- name: 'command get deployment'
  shell: "{{command_cmd_get_deployment}}"
  register: register_deployment
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set deployment'
  command: "{{command_cmd_set_deployment}}"
  when: not (hostname_deployment == '') and not (register_deployment.stdout == hostname_deployment)
  tags:
    - hostname

- name: 'command get hostname'
  shell: "{{command_cmd_get_hostname}}"
  register: register_hostname
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set hostname'
  command: "{{command_cmd_set_hostname}}"
  when: not (register_hostname.stdout == hostname_hostname)
  tags:
    - hostname

- name: 'command get icon-name'
  shell: "{{command_cmd_get_icon_name}}"
  register: register_icon_name
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set icon-name'
  command: "{{command_cmd_set_icon_name}}"
  when: not (hostname_icon_name == '') and not (register_icon_name.stdout == hostname_icon_name)
  tags:
    - hostname

- name: 'command get location'
  shell: "{{command_cmd_get_location}}"
  register: register_location
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set location'
  command: "{{command_cmd_set_location}}"
  when: not (hostname_location == '') and not (register_location.stdout == hostname_location)
  tags:
    - hostname

- name: 'command get pretty-hostname'
  shell: "{{command_cmd_get_pretty_hostname}}"
  register: register_pretty_hostname
  changed_when: False
  check_mode: 'no'
  tags:
    - hostname

- name: 'command set pretty-hostname'
  command: "{{command_cmd_set_pretty_hostname}}"
  when: not (hostname_pretty_hostname == '') and not (register_pretty_hostname.stdout == hostname_pretty_hostname)
  tags:
    - hostname
