---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - vim

- name: 'package remove vim'
  package:
    state: 'absent'
    name: "{{package_name_vim}}"
    install_recommends: 'no'
  tags:
    - vim

- name: 'file remove vimrc'
  file:
    state: 'absent'
    path: "{{file_dst_vimrc}}"
  tags:
    - vim
