---

alertmanager_state: 'enable'

alertmanager_config: ''

alertmanager_monit_state: False

alertmanager_nftables_filter_rule: |
  add rule ip filter INPUT ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } ct state new tcp dport { 9093, 9093 } counter accept comment "alertmanager from internal private addresses"
  add rule ip6 filter INPUT ip6 saddr fc00::/7 ct state new tcp dport { 9093, 9093 } counter accept comment "alertmanager from unique local addresses"
  add rule ip filter OUTPUT ct state new tcp dport 25 counter accept comment "smtp to any"
  add rule ip6 filter OUTPUT ct state new tcp dport 25 counter accept comment "smtp to any"
  add rule ip filter OUTPUT ct state new tcp dport { 465, 587 } counter accept comment "smtps to any"
  add rule ip6 filter OUTPUT ct state new tcp dport { 465, 587 } counter accept comment "smtps to any"

alertmanager_nftables_state: False

alertmanager_version: '0.31.1'

alertmanager_web_external_url: "https://alertmanager.{{ansible_domain}}"
