---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - gdisk

- name: remove package gdisk
  package:
    state: 'absent'
    name: "{{package_name_gdisk}}"
    install_recommends: 'no'
  tags:
    - gdisk
