---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command systemctl daemon-reload'
  command: "{{command_cmd_systemctl_daemon_reload}}"

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service restart grafana'
  service:
    state: 'restarted'
    name: "{{service_name_grafana}}"

- name: 'service reload monit'
  service:
    state: 'reloaded'
    name: "{{service_name_monit}}"
  when: (register_check_service_monit.rc == 0)

- name: 'service restart prometheus'
  service:
    state: 'restarted'
    name: "{{service_name_prometheus}}"
