---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - zfs

- name: 'cron remove zfs_check-pools'
  cron:
    state: 'absent'
    name: "{{cron_name_zfs_check_pools}}"
    cron_file: "{{cron_cron_file_zfs_check_pools}}"
    user: "{{cron_user_zfs_scrub_pools}}"
  tags:
    - zfs

- name: 'file remove zfs_check-pools'
  file:
    state: 'absent'
    path: "{{file_dst_zfs_check_pools}}"
  tags:
    - zfs

- name: 'cron remove zfs_scrub-pools'
  cron:
    state: 'absent'
    name: "{{cron_name_zfs_scrub_pools}}"
    cron_file: "{{cron_cron_file_zfs_scrub_pools}}"
    user: "{{cron_user_zfs_scrub_pools}}"
  tags:
    - zfs

- name: 'file remove zfs_scrub-pools'
  file:
    state: 'absent'
    path: "{{file_src_zfs_scrub_pools}}"
  tags:
    - zfs

- name: 'cron remove zfs_trim-pools'
  cron:
    state: 'absent'
    name: "{{cron_name_zfs_trim_pools}}"
    cron_file: "{{cron_cron_file_zfs_trim_pools}}"
    user: "{{cron_user_zfs_trim_pools}}"
  tags:
    - zfs

- name: 'file remove zfs_trim-pools'
  file:
    state: 'absent'
    path: "{{file_src_zfs_trim_pools}}"
  tags:
    - zfs
