---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - systemd

- name: create file config
  template:
    src: "{{file_src_config}}"
    dest: "{{file_dst_systemd}}/{{(item.mode|default('system'))}}/{{(item.name|default('config'))}}.{{(item.type|default('target'))}}"
    mode: "{{file_mode_config}}"
    owner: "{{file_owner_config}}"
    group: "{{file_group_config}}"
  loop: "{{systemd_config_all + systemd_config_group + systemd_config_host}}"
  when: not (item.state is match('false|no|remove'))
  tags:
    - systemd

- name: remove file config
  file:
    state: absent
    dest: "{{file_dst_systemd}}/{{(item.mode|default('system'))}}/{{(item.name|default('config'))}}.{{(item.type|default('target'))}}"
  loop: "{{systemd_config_all + systemd_config_group + systemd_config_host}}"
  when: (item.state is match('false|no|remove'))
  tags:
    - systemd
