---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_memos

- name: create file pod_memos.yaml
  template:
    src: "{{file_src_pod_memos_yaml}}"
    dest: "{{file_dst_pod_memos_yaml}}"
    mode: "{{file_mode_pod_memos_yaml}}"
    owner: "{{file_owner_pod_memos_yaml}}"
    group: "{{file_group_pod_memos_yaml}}"
  tags:
    - pod_memos

- name: create file pod_memos.default
  template:
    src: "{{file_src_pod_memos_default}}"
    dest: "{{file_dst_pod_memos_default}}"
    mode: "{{file_mode_pod_memos_default}}"
    owner: "{{file_owner_pod_memos_default}}"
    group: "{{file_group_pod_memos_default}}"
  tags:
    - pod_memos

- name: remove file pod_memos-memos.cfg
  file:
    state: absent
    path: "{{file_dst_pod_memos_memos_cfg}}"
  notify: reload monit
  tags:
    - pod_memos

- name: create file pod_memos.nft
  template:
    src: "{{file_src_pod_memos_nft}}"
    dest: "{{file_dst_pod_memos_nft}}"
    mode: "{{file_mode_pod_memos_nft}}"
    owner: "{{file_owner_pod_memos_nft}}"
    group: "{{file_group_pod_memos_nft}}"
  notify:
    - validate nftables
    - reload nftables
  when: (pod_memos_nftables_state == True)
  tags:
    - pod_memos

- name: remove file pod_memos.nft
  file:
    state: absent
    path: "{{file_dst_pod_memos_nft}}"
  notify: reload nftables
  when: (pod_memos_nftables_state == False)
  tags:
    - pod_memos

- name: stop service pod_memos
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_memos}}"
    daemon_reload: True
  tags:
    - pod_memos
