---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_memos

- name: check service pod_memos
  shell: "{{command_cmd_check_service_pod_memos}}"
  register: register_check_service_pod_memos
  changed_when: (register_check_service_pod_memos.rc == 0)
  failed_when: (register_check_service_pod_memos.rc > 1)
  check_mode: False
  tags:
    - pod_memos

- name: stop service pod_memos
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_memos}}"
    daemon_reload: True
  when: (register_check_service_pod_memos.rc == 0)
  tags:
    - pod_memos

- name: remove file pod_memos.nft
  file:
    state: absent
    path: "{{file_dst_pod_memos_nft}}"
  notify: reload nftables
  tags:
    - pod_memos

- name: remove file pod_memos-memos.cfg
  file:
    state: absent
    path: "{{file_dst_pod_memos_memos_cfg}}"
  notify: reload monit
  tags:
    - pod_memos

- name: remove file pod_memos_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_memos_etc_dir}}"
  tags:
    - pod_memos

- name: remove file pod_memos.default
  file:
    state: absent
    path: "{{file_dst_pod_memos_default}}"
  tags:
    - pod_memos

- name: remove file pod_memos.service
  file:
    state: absent
    path: "{{file_dst_pod_memos_service}}"
  tags:
    - pod_memos
