---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_step_ca

- name: create file pod_step_ca.yaml
  template:
    src: "{{file_src_pod_step_ca_yaml}}"
    dest: "{{file_dst_pod_step_ca_yaml}}"
    mode: "{{file_mode_pod_step_ca_yaml}}"
    owner: "{{file_owner_pod_step_ca_yaml}}"
    group: "{{file_group_pod_step_ca_yaml}}"
  no_log: True
  notify: restart service pod_step_ca
  tags:
    - pod_step_ca

- name: create file pod_step_ca.default
  template:
    src: "{{file_src_pod_step_ca_default}}"
    dest: "{{file_dst_pod_step_ca_default}}"
    mode: "{{file_mode_pod_step_ca_default}}"
    owner: "{{file_owner_pod_step_ca_default}}"
    group: "{{file_group_pod_step_ca_default}}"
  notify: restart service pod_step_ca
  tags:
    - pod_step_ca

- name: create file pod_step_ca-step_ca.cfg
  template:
    src: "{{file_src_pod_step_ca_step_ca_cfg}}"
    dest: "{{file_dst_pod_step_ca_step_ca_cfg}}"
    mode: "{{file_mode_pod_step_ca_step_ca_cfg}}"
    owner: "{{file_owner_pod_step_ca_step_ca_cfg}}"
    group: "{{file_group_pod_step_ca_step_ca_cfg}}"
  notify:
    - validate monit
    - reload monit
  when: (pod_step_ca_monitor_monit_state == True)
  tags:
    - pod_step_ca

- name: remove file pod_step_ca-step_ca.cfg
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_step_ca_cfg}}"
  notify: reload monit
  when: (pod_step_ca_monitor_monit_state == False)
  tags:
    - pod_step_ca

- name: create file pod_step_ca.nft
  template:
    src: "{{file_src_pod_step_ca_nft}}"
    dest: "{{file_dst_pod_step_ca_nft}}"
    mode: "{{file_mode_pod_step_ca_nft}}"
    owner: "{{file_owner_pod_step_ca_nft}}"
    group: "{{file_group_pod_step_ca_nft}}"
  notify:
    - validate nftables
    - reload nftables
  when: (pod_step_ca_nftables_state == True)
  tags:
    - pod_step_ca

- name: remove file pod_step_ca.nft
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_nft}}"
  notify: reload nftables
  when: (pod_step_ca_nftables_state == False)
  tags:
    - pod_step_ca

- name: start service pod_step_ca
  service:
    state: started
    enabled: True
    name: "{{service_name_pod_step_ca}}"
    daemon_reload: True
  tags:
    - pod_step_ca
