---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_step_ca

- name: create file pod_step_ca_etc.dir
  file:
    state: directory
    path: "{{file_dst_pod_step_ca_etc_dir}}"
    mode: "{{file_mode_pod_step_ca_etc_dir}}"
    owner: "{{file_owner_pod_step_ca_etc_dir}}"
    group: "{{file_group_pod_step_ca_etc_dir}}"
  tags:
    - pod_step_ca

- name: create file opt.dir
  file:
    state: directory
    path: "{{file_dst_opt_dir}}"
    mode: "{{file_mode_opt_dir}}"
    owner: "{{file_owner_opt_dir}}"
    group: "{{file_group_opt_dir}}"
  tags:
    - pod_step_ca

- name: create file pod_step_ca_opt.dir
  file:
    state: directory
    path: "{{file_dst_pod_step_ca_opt_dir}}"
    mode: "{{file_mode_pod_step_ca_opt_dir}}"
    owner: "{{file_owner_pod_step_ca_opt_dir}}"
    group: "{{file_group_pod_step_ca_opt_dir}}"
  tags:
    - pod_step_ca

- name: create file step_ca_data.dir
  file:
    state: directory
    path: "{{file_dst_step_ca_data_dir}}"
    mode: "{{file_mode_step_ca_data_dir}}"
    owner: "{{file_owner_step_ca_data_dir}}"
    group: "{{file_group_step_ca_data_dir}}"
  tags:
    - pod_step_ca

- name: create file pod_step_ca.service
  template:
    src: "{{file_src_pod_step_ca_service}}"
    dest: "{{file_dst_pod_step_ca_service}}"
    mode: "{{file_mode_pod_step_ca_service}}"
    owner: "{{file_owner_pod_step_ca_service}}"
    group: "{{file_group_pod_step_ca_service}}"
  tags:
    - pod_step_ca

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (pod_step_ca_monit_state == True)
  tags:
    - pod_step_ca

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (pod_step_ca_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - pod_step_ca

- name: stat file nftables.d
  stat:
    path: "{{file_dst_nftables_d}}"
  register: register_nftables_d
  when: (pod_step_ca_nftables_state == True)
  tags:
    - pod_step_ca

- name: create file nftables.d
  file:
    state: directory
    path: "{{file_dst_nftables_d}}"
    mode: "{{file_mode_nftables_d}}"
    owner: "{{file_owner_nftables_d}}"
    group: "{{file_group_nftables_d}}"
  when: (pod_step_ca_nftables_state == True) and (register_nftables_d.stat.exists == False)
  tags:
    - pod_step_ca
