---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - pod_step_ca

- name: check service pod_step_ca
  shell: "{{command_cmd_check_service_pod_step_ca}}"
  register: register_check_service_pod_step_ca
  changed_when: (register_check_service_pod_step_ca.rc == 0)
  failed_when: (register_check_service_pod_step_ca.rc > 1)
  check_mode: False
  tags:
    - pod_step_ca

- name: stop service pod_step_ca
  service:
    state: stopped
    enabled: False
    name: "{{service_name_pod_step_ca}}"
    daemon_reload: True
  when: (register_check_service_pod_step_ca.rc == 0)
  tags:
    - pod_step_ca

- name: remove file pod_step_ca.nft
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_nft}}"
  notify: reload nftables
  tags:
    - pod_step_ca

- name: remove file pod_step_ca-step_ca.cfg
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_step_ca_cfg}}"
  notify: reload monit
  tags:
    - pod_step_ca

- name: remove file pod_step_ca_etc.dir
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_etc_dir}}"
  tags:
    - pod_step_ca

- name: remove file pod_step_ca.default
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_default}}"
  tags:
    - pod_step_ca

- name: remove file pod_step_ca.service
  file:
    state: absent
    path: "{{file_dst_pod_step_ca_service}}"
  tags:
    - pod_step_ca
