---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'group create node_exporter'
  group:
    state: 'present'
    name: "{{group_name_node_exporter}}"
    system: "{{group_system_node_exporter}}"
  tags:
    - install
    - node_exporter

- name: 'user create node_exporter'
  user:
    state: 'present'
    name: "{{user_name_node_exporter}}"
    comment: "{{user_comment_node_exporter}}"
    group: "{{user_group_node_exporter}}"
    append: "{{user_append_node_exporter}}"
    createhome: "{{user_home_create_node_exporter}}"
    move_home: "{{user_home_move_node_exporter}}"
    remove: "{{user_home_remove_node_exporter}}"
    force: "{{user_home_force_node_exporter}}"
    password: "{{user_password_node_exporter}}"
    update_password: "{{user_password_update_node_exporter}}"
    shell: "{{user_shell_node_exporter}}"
    system: "{{user_system_node_exporter}}"
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create node_exporter_data.dir'
  file:
    state: 'directory'
    path: "{{file_dst_node_exporter_data_dir}}"
    mode: "{{file_mode_node_exporter_data_dir}}"
    owner: "{{file_owner_node_exporter_data_dir}}"
    group: "{{file_group_node_exporter_data_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file create textfile_collector.dir'
  file:
    state: 'directory'
    path: "{{file_dst_textfile_collector_dir}}"
    mode: "{{file_mode_textfile_collector_dir}}"
    owner: "{{file_owner_textfile_collector_dir}}"
    group: "{{file_group_textfile_collector_dir}}"
  tags:
    - install
    - node_exporter

- name: 'file download node_exporter.tar.gz'
  get_url:
    url: "{{file_src_node_exporter_tar_gz}}"
    dest: "{{file_dst_node_exporter_tar_gz}}"
    mode: "{{file_mode_node_exporter_tar_gz}}"
    owner: "{{file_owner_node_exporter_tar_gz}}"
    group: "{{file_group_node_exporter_tar_gz}}"
    checksum: "{{file_checksum_node_exporter_tar_gz}}"
  tags:
    - install
    - node_exporter

- name: 'file unarchive node_exporter'
  unarchive:
    src: "{{file_src_node_exporter}}"
    dest: "{{file_dst_node_exporter}}"
    owner: "{{file_owner_node_exporter}}"
    group: "{{file_group_node_exporter}}"
    exclude: "{{file_exclude_node_exporter}}"
    extra_opts: "{{file_extra_opts_node_exporter}}"
    remote_src: 'yes'
  tags:
    - install
    - node_exporter

- name: 'file create node_exporter.service'
  template:
    src: "{{file_src_node_exporter_service}}"
    dest: "{{file_dst_node_exporter_service}}"
    mode: "{{file_mode_node_exporter_service}}"
    owner: "{{file_owner_node_exporter_service}}"
    group: "{{file_group_node_exporter_service}}"
  notify: 'command systemctl daemon-reload'
  tags:
    - install
    - node_exporter

- name: 'stat file monit.d'
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (node_exporter_monitor_monit_state is match('true|yes|enable'))
  tags:
    - install
    - node_exporter

- name: 'file create monit.d'
  file:
    state: 'directory'
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (node_exporter_monitor_monit_state is match('true|yes|enable')) and (register_monit_d.stat.exists == False)
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# COMMANDS
#-------------------------------------------------------------------------------

- name: 'command check service monit'
  shell: "{{command_cmd_check_service_monit}}"
  register: register_check_service_monit
  changed_when: (register_check_service_monit.rc > 1)
  failed_when: (register_check_service_monit.rc > 1)
  check_mode: 'no'
  when: (node_exporter_monitor_monit_state is match('true|yes|enable'))
  tags:
    - install
    - node_exporter

#-------------------------------------------------------------------------------
# META
#-------------------------------------------------------------------------------

- name: 'meta flush handlers'
  meta: 'flush_handlers'
  tags:
    - install
    - node_exporter
