---

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - tmux

- name: 'package install tmux'
  package:
    state: 'present'
    name: "{{package_name_tmux}}"
    install_recommends: 'no'
  tags:
    - tmux

- name: 'file create tmux.conf'
  template:
    src: "{{file_src_tmux_conf}}"
    dest: "{{file_dst_tmux_conf}}"
    mode: "{{file_mode_tmux_conf}}"
    owner: "{{file_owner_tmux_conf}}"
    group: "{{file_group_tmux_conf}}"
  tags:
    - tmux
