---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - remove
    - sudo

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove sudo'
  package:
    state: 'absent'
    name: "{{package_name_sudo}}"
    install_recommends: 'no'
  tags:
    - remove
    - sudo

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove sudoers'
  file:
    state: 'absent'
    path: "{{file_dst_sudoers}}"
  tags:
    - remove
    - sudo

- name: 'file remove sudoers.d'
  file:
    state: 'absent'
    path: "{{file_dst_sudoers_d}}"
  tags:
    - remove
    - sudo
