---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - rsyslog

- name: install package rsyslog
  package:
    state: present
    name: "{{package_name_rsyslog}}"
    install_recommends: False
  tags:
    - rsyslog

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (rsyslog_monit_state == True)
  tags:
    - rsyslog

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (rsyslog_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - rsyslog

- name: stat file nftables.d
  stat:
    path: "{{file_dst_nftables_d}}"
  register: register_nftables_d
  when: (rsyslog_nftables_state == True)
  tags:
    - rsyslog

- name: create file nftables.d
  file:
    state: directory
    path: "{{file_dst_nftables_d}}"
    mode: "{{file_mode_nftables_d}}"
    owner: "{{file_owner_nftables_d}}"
    group: "{{file_group_nftables_d}}"
  when: (rsyslog_nftables_state == True) and (register_nftables_d.stat.exists == False)
  tags:
    - rsyslog
