---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - fstrim

- name: remove cron fstrim_discard-blocks
  cron:
    state: 'absent'
    name: "{{cron_name_fstrim_discard_blocks}}"
    cron_file: "{{cron_cron_file_fstrim_discard_blocks}}"
    user: "{{cron_user_fstrim_discard_blocks}}"
  tags:
    - fstrim

- name: remove file fstrim_discard-blocks
  file:
    state: 'absent'
    path: "{{file_dst_fstrim_discard_blocks}}"
  tags:
    - fstrim
