---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - haproxy

- name: install package openssl
  package:
    state: present
    name: "{{package_name_openssl}}"
    install_recommends: False
  tags:
    - haproxy

- name: install package haproxy
  package:
    state: present
    name: "{{package_name_haproxy}}"
    install_recommends: False
  tags:
    - haproxy

- name: stat file dhparam.pem
  stat:
    path: "{{file_dst_dhparam_pem}}"
  register: register_dhparam_pem
  tags:
    - haproxy

- name: generate dhparam
  shell: "{{command_cmd_generate_dhparam}}"
  check_mode: False
  when: (register_dhparam_pem.stat.exists == False)
  tags:
    - haproxy

- name: stat file monit.d
  stat:
    path: "{{file_dst_monit_d}}"
  register: register_monit_d
  when: (haproxy_monit_state == True)
  tags:
    - haproxy

- name: create file monit.d
  file:
    state: directory
    path: "{{file_dst_monit_d}}"
    mode: "{{file_mode_monit_d}}"
    owner: "{{file_owner_monit_d}}"
    group: "{{file_group_monit_d}}"
  when: (haproxy_monit_state == True) and (register_monit_d.stat.exists == False)
  tags:
    - haproxy

- name: stat file nftables.d
  stat:
    path: "{{file_dst_nftables_d}}"
  register: register_nftables_d
  when: (haproxy_nftables_state == True)
  tags:
    - haproxy

- name: create file nftables.d
  file:
    state: directory
    path: "{{file_dst_nftables_d}}"
    mode: "{{file_mode_nftables_d}}"
    owner: "{{file_owner_nftables_d}}"
    group: "{{file_group_nftables_d}}"
  when: (haproxy_nftables_state == True) and (register_nftables_d.stat.exists == False)
  tags:
    - haproxy
