---

- name: include variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "vars/{{ansible_distribution_major_version}}.yml"
        - 'vars/main.yml'
  tags:
    - restic

- name: create cron restic_run-backup
  cron:
    state: 'present'
    disabled: 'yes'
    name: "{{cron_name_restic_run_backup}}"
    cron_file: "{{cron_cron_file_restic_run_backup}}"
    day: "{{cron_day_restic_run_backup}}"
    hour: "{{cron_hour_restic_run_backup}}"
    minute: "{{cron_minute_restic_run_backup}}"
    month: "{{cron_month_restic_run_backup}}"
    weekday: "{{cron_weekday_restic_run_backup}}"
    user: "{{cron_user_restic_run_backup}}"
    job: "{{cron_job_restic_run_backup}}"
  tags:
    - restic
